#!/usr/bin/env bash

set -euo pipefail

# Invariant smoke checks: fail-closed detection behavior and bounded-runtime guards.
go test ./internal/pipeline ./internal/helius ./internal/exports -run 'TestEvaluateCandidate_BlocksOnUnknownRequiredGate|TestMaterializeCandidatesMinInjectionUnknownWhenDustUnknownCouldMeetThreshold|TestMaterializeCandidatesMinInjectionIgnoresNonBaseGateInboundEvents|TestMaterializeCandidatesFailsClosedOnInvalidParams|TestRunWalletCoreSyncBaselineTruncationForcesIncompleteAndSuppressesCandidates|TestRunWalletCoreSyncRejectsInvalidLookalikeThresholds|TestValidateCoreSyncParamsRejectsInvalidRuntimeBounds|TestRetryBackoffClampsLargeAttemptsWithoutOverflow|TestNewHTTPClientRequiresAbsoluteHTTPBaseURL|TestExportDatasetDeterministicAcrossInputOrder'
