name: Trigger auto deployment for poisontrace-dev

on:
  push:
    branches:
      - main
    paths:
      - "**"
      - ".github/workflows/poisontrace-dev-AutoDeployTrigger-873c7aec-1ecf-4c2f-833a-4fafe517ddf7.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ secrets.POISONTRACEDEV_AZURE_CLIENT_ID != '' && secrets.POISONTRACEDEV_AZURE_TENANT_ID != '' && secrets.POISONTRACEDEV_AZURE_SUBSCRIPTION_ID != '' && secrets.POISONTRACEDEV_REGISTRY_URL != '' && secrets.POISONTRACEDEV_REGISTRY_USERNAME != '' && secrets.POISONTRACEDEV_REGISTRY_PASSWORD != '' }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.POISONTRACEDEV_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.POISONTRACEDEV_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.POISONTRACEDEV_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: deploy/docker/Dockerfile
          registryUrl: ${{ secrets.POISONTRACEDEV_REGISTRY_URL }}
          registryUsername: ${{ secrets.POISONTRACEDEV_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.POISONTRACEDEV_REGISTRY_PASSWORD }}
          containerAppName: poisontrace-dev
          resourceGroup: rg-poisontrace-p0p1-dev-sea
          imageToBuild: ${{ secrets.POISONTRACEDEV_REGISTRY_URL }}/poisontrace-dev:${{ github.sha }}
